
-- ACTIVATE CHANGE TRACKING AT THE DATABASE LEVEL
ALTER DATABASE [$(DATABASE)]
    SET CHANGE_TRACKING = ON
    (CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON);
GO

-- ACTIVATE CHANGE TRACKING ON THE TABLES
ALTER TABLE SalesLT.Customer
	ENABLE CHANGE_TRACKING
    WITH (TRACK_COLUMNS_UPDATED = ON);
GO 

ALTER TABLE SalesLT.Address
    ENABLE CHANGE_TRACKING;
GO

ALTER TABLE SalesLT.CustomerAddress
    ENABLE CHANGE_TRACKING;
GO

ALTER TABLE SalesLT.Product
    ENABLE CHANGE_TRACKING
    WITH (TRACK_COLUMNS_UPDATED = ON);
GO

ALTER TABLE SalesLT.ProductModel
    ENABLE CHANGE_TRACKING;
GO

ALTER TABLE SalesLT.ProductCategory
    ENABLE CHANGE_TRACKING;
GO

ALTER TABLE SalesLT.ProductDescription
    ENABLE CHANGE_TRACKING;
GO

ALTER TABLE SalesLT.ProductModelProductDescription
    ENABLE CHANGE_TRACKING;
GO

PRINT 'CHANGE TRACKING ACTIVATED SUCCESSFULLY';
GO
